# Site settings
name: Melissa J. Barca
email: melissajoldhambarca@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, C++, Java, JavaScript, GWT, SQL, DB2, Software Design, Relational Databases, Agile, Software Architecture"
skills: "Software Engineer in Portland, ME"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/melissa-oldham-barca-01891680
  - title: instagram
    url: https://instagram.com/melissajene
  - title: github
    url: https://github.com/melissa-barca
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 67AECA
  primary-rgb: "103, 174, 202"
  secondary: 675682
  secondary-dark: 5F0F4E
  #section-tout: E52A6F



# Build settings
markdown: kramdown
permalink: pretty
